console.log("aaabbb")
console.log("gfds")
console.log(12364578)
console.log(12364.578)

console.log("aaaa'vvvv")
console.log('ccccc\'csacsa')
console.log(true)
console.log(false)
console.log(5-2)
console.log(5+2)
console.log("5" + "2")
console.log("asd" * "zxcs")
console.log("asd" + "zxcs")
console.log("5" - "2")
console.log("5" * "2")
console.log("5" / "2")
console.log(8**3)
console.log(9%4)

